# Generated by Django 2.0.8 on 2018-08-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAgencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajero',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='viajero',
            old_name='first_name',
            new_name='nombre',
        ),
    ]
