# Generated by Django 2.0.8 on 2018-08-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionAgencia', '0004_auto_20180821_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='retorno',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='salida',
        ),
    ]
